---
- name: install apache2 to berry
  hosts: webservers
  become: yes
  vars: 
    port: 80
    email: samuelfatoki7@gmail.com
    domain: 54.160.181.192
    master: akinfatoki7@gmail.com
    server_name: laravel
  tasks: 
     - name: install apache2 package
       package: 
           name: apache2
           state: latest
           update_cache: yes
     - name: start apache2
       service: 
           name: apache2
           state: started
     - name: add firewall rule
       firewalld:
            port: 80/tcp
            permanent: true
            state: enabled
     - name: restart firewalld
       service:
            name: firewalld
            state: restarted
     - name: copy laravel.conf into apache directory
       template: 
            src: /home/akinkunmi/laravel.conf
            dest: /etc/apache2/sites-available/
     - name: a2enmod laravel.conf
       command: a2enmod rewrite
     - name: a2ensite laravel.conf
       command: a2ensite "{{ server_name }}".conf
     - name: dissite apache default config file
       command: a2dissite 000-default.conf
     - name: restart apache2
       service:
           name: apache2
           state: restarted
